name: 06 - Contexts

on:
  push:
  workflow_dispatch:

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display Information
              run: |
                Event name: ${{ github.event_name }}

                Ref: ${{ github.ref }}

                SHA: ${{ github.sha }}

                Actor: ${{ github.actor }}

                Workflow: ${{ github.workflow }}

                Run ID: ${{ github.run_id }}

                Run number: ${{ github.run_number }}

                Repository: ${{ github.repository }}

            - name: Retrieve Variable
              run: echo "The value of MY_VAR is ${{ vars.MY_VAR }}"