name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{inputs.debug}}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
        description: 'Set to true to enable debug mode'

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display Information
              run: |
                echo "Event name: ${{ github.event_name }}"

                echo "Ref: ${{ github.ref }}"

                echo "SHA: ${{ github.sha }}"

                echo "Actor: ${{ github.actor }}"

                echo "Workflow: ${{ github.workflow }}"

                echo "Run ID: ${{ github.run_id }}"

                echo "Run number: ${{ github.run_number }}"

                echo "Repository: ${{ github.repository }}"

            - name: Retrieve Variable
              run: echo "The value of MY_VAR is ${{ vars.MY_VAR }}"