name: 07 - Expressions

on: 
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
                description: 'Set to true to enable debug mode'

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "[debug] Print start-up data"
              if: ${{ inputs.debug }} 
              run: |

                  echo "Triggered by: ${{ github.actor }}"

                  echo "Branch: ${{ github.ref }}"

                  echo "Commit SHA: ${{ github.sha }}"

                  echo "Runner OS: ${{ runner.os }}"

            - name: "[debug] Print when triggered from main"
              if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
              run: |
                echo "Triggered by: ${{ github.actor }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ runner.os }}"
            - name: "Greetings"
              run: echo "Hello, world!"

