name: 13 - Caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                default: true
                description: "Where to execute cache step"
            node-version:
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
                default:
                    20.x
                description: "Node version selection"
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run: 
              working-directory: 13-caching/react-app  
        #1. Checkout code
        #2. Install dependencies
        #3. Liniting, Formatting, Unit testing, building
        #4. Deploy
        steps:
            - name:  "Checkout code"
              uses: actions/checkout@v4  
            - name: "Setup Node"
              uses: actions/setup-node@v3
              with:
                node-version: ${{ inputs.node-version }}
            - name: "Install dependencies"
              run: npm ci
            - name: "Testing"
              run: npm run test
            - name: "Building"
              run: npm run build
            - name: "Deploying to nonprod"
              run: echo "Deploying to nonprod"